---
deployment:
  tasks:
    - export DEPLOYPATH=/home/n1604046/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp assets/css/style.css $DEPLOYPATH
    - /bin/cp -R assets/img $DEPLOYPATH